name: grow_right_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  go_router: ^16.1.0
  tflite_flutter: ^0.11.0
  google_fonts: ^6.3.0
  flutter_launcher_icons: ^0.14.4
  circle_nav_bar: ^2.2.0
  hugeicons: ^0.0.11
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  animated_custom_dropdown: ^3.1.1
  flutter_svg: ^2.2.0
  image_picker: ^1.1.2


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/tflite_models/coffee_model/
    - assets/tflite_models/mango_model/
    - assets/tflite_models/soil_model/
    - assets/tflite_models/Wheat_model/



